// Player-facing text lives here, separate from component logic, so the
// copy lint (tests/copy-lint.test.ts) can scan every string in one place
// and so a future content pipeline can localize or data-drive it without
// touching component code. See docs/CONTENT_GUIDE.md.
//
// Rule: no em dash, no semicolon, anywhere in these values.

export const copy = {
  title: "Sector Dynasties",
  subtitle: "A dynasty grows one generation at a time.",
  timeControlsLabel: "Time controls",
  advanceOneYear: "Advance one year",
  advanceYearsLabel: "Years to advance",
  advanceYearsButton: "Advance",
  yearLabel: "Year",
  populationLabel: "Population under your influence",
  wealthLabel: "Dynasty wealth",
  citiesLabel: "Cities",
  systemsLabel: "Star systems",
  loading: "Generating the sector...",
  sectorBrowserTitle: "Sector browser",
  browserCitiesLabel: "Known cities",
  browserTreasuryLabel: "City treasury",
  cityPopulationLabel: "Population",
  cityTreasuryLabel: "Treasury",
  cityDetailEyebrow: "Selected city",
  cityDetailEmptyTitle: "No city selected",
  cityDetailEmptyBody: "Choose a city from the sector browser.",
  citySpecializationLabel: "Specialization",
  cityAverageWealthLabel: "Average wealth",
  cityUnemploymentLabel: "Unemployment",
  planetsCount: (count: number) => `${count} ${count === 1 ? "planet" : "planets"}`,
  governmentHeading: "Government",
  governmentFederalismLabel: "Federalism",
  governmentFranchiseLabel: "Franchise",
  governmentEconomicLiberalismLabel: "Economic liberalism",
  governmentPressFreedomLabel: "Press freedom",
  governmentLegislativeStrengthLabel: "Legislative strength",
  governmentJudicialIndependenceLabel: "Judicial independence",
  lobbyFormTitle: (cost: string) => `Spend ${cost} to shift a policy`,
  lobbyComponentLabel: "Policy",
  lobbyDirectionLabel: "Direction",
  lobbyDirectionIncrease: "Increase",
  lobbyDirectionDecrease: "Decrease",
  lobbySubmit: "Lobby",
  lobbyOutcome: (component: string, before: string, after: string) =>
    `${component} moved from ${before} to ${after}.`,
  lobbyError: (message: string) => `Lobbying failed. ${message}`,
  dynastyPanelTitle: "Dynasty",
  dynastyRoleHead: "Head of the dynasty",
  dynastyRoleMember: "Family member",
  dynastyStatusAlive: "Living",
  dynastyStatusDeceased: "Deceased",
  dynastyAge: (years: number) => `${years} ${years === 1 ? "year" : "years"} old`,
  saveControlsLabel: "Save and load",
  saveButton: "Save",
  loadButton: "Load",
  defaultSaveSlotName: "Quick save",
  saveStatusIdle: "No save yet.",
  saveStatusSaved: (savedAt: string) => `Saved at ${savedAt}.`,
  saveStatusLoaded: (savedAt: string) => `Loaded save from ${savedAt}.`,
  saveStatusError: (message: string) => `Save failed. ${message}`,
  globalSearchLabel: "Search",
  globalSearchPlaceholder: "Search characters and cities",
  globalSearchResultsLabel: "Search results",
  globalSearchCharacterKindLabel: "Character",
  globalSearchCityKindLabel: "City",
  globalSearchCityLocation: (planetName: string, countryName: string) =>
    `${countryName}, ${planetName}`,
  globalSearchNoResults: (query: string) => `No characters or cities match "${query}".`,
  navGalaxy: "Galaxy",
  navDynasty: "Dynasty",
  navEconomy: "Economy",
  navEvents: "Events",
  eventsScreenTitle: "Pending decisions",
  eventsScreenEmpty: "No decisions await the dynasty right now.",
  eventRaisedYear: (year: number) => `Raised in year ${year}`,
  eventResolveError: (message: string) => `Could not resolve this event. ${message}`,
  economyScreenTitle: "Economy",
  businessesHeading: "Businesses",
  businessesEmpty: "The dynasty owns no businesses yet.",
  businessEquityLabel: "Equity",
  foundBusinessButton: "Found a business",
  foundBusinessFormTitle: "Found a new business",
  foundBusinessNameLabel: "Business name",
  foundBusinessArchetypeLabel: "Archetype",
  foundBusinessCityLabel: "Host city",
  foundBusinessSubmit: "Found business",
  foundBusinessCancel: "Cancel",
  foundBusinessError: (message: string) => `Could not found this business. ${message}`,
  foundBusinessNoEligibleCities: "No city currently supports this archetype.",
  tradeRoutesHeading: "Trade routes",
  tradeRoutesEmpty: "No trade routes have been established yet.",
  tradeRouteCapacityLabel: "Capacity",
  tradeRouteDistanceLabel: "Distance",
  tradeRouteCostLabel: "Weekly cost",
  tradeRouteReliabilityLabel: "Reliability",
  careersHeading: "Careers",
  careersEmpty: "No family members currently hold a job.",
};
