// Player-facing text lives here, separate from component logic, so the
// copy lint (tests/copy-lint.test.ts) can scan every string in one place
// and so a future content pipeline can localize or data-drive it without
// touching component code. See docs/CONTENT_GUIDE.md.
//
// Rule: no em dash, no semicolon, anywhere in these values.

export const copy = {
  title: "Sector Dynasties",
  subtitle: "A dynasty grows one generation at a time.",
  timeControlsLabel: "Time controls",
  advanceOneYear: "Advance one year",
  advanceYearsLabel: "Years to advance",
  advanceYearsButton: "Advance",
  yearLabel: "Year",
  populationLabel: "Population under your influence",
  wealthLabel: "Dynasty wealth",
  citiesLabel: "Cities",
  systemsLabel: "Star systems",
  loading: "Generating the sector...",
  sectorBrowserTitle: "Sector browser",
  browserCitiesLabel: "Known cities",
  browserTreasuryLabel: "City treasury",
  cityPopulationLabel: "Population",
  cityTreasuryLabel: "Treasury",
  cityDetailEyebrow: "Selected city",
  cityDetailEmptyTitle: "No city selected",
  cityDetailEmptyBody: "Choose a city from the sector browser.",
  citySpecializationLabel: "Specialization",
  cityAverageWealthLabel: "Average wealth",
  cityUnemploymentLabel: "Unemployment",
  planetsCount: (count: number) => `${count} ${count === 1 ? "planet" : "planets"}`,
  dynastyPanelTitle: "Dynasty",
  dynastyRoleHead: "Head of the dynasty",
  dynastyRoleMember: "Family member",
  dynastyStatusAlive: "Living",
  dynastyStatusDeceased: "Deceased",
  dynastyAge: (years: number) => `${years} ${years === 1 ? "year" : "years"} old`,
  saveControlsLabel: "Save and load",
  saveButton: "Save",
  loadButton: "Load",
  defaultSaveSlotName: "Quick save",
  saveStatusIdle: "No save yet.",
  saveStatusSaved: (savedAt: string) => `Saved at ${savedAt}.`,
  saveStatusLoaded: (savedAt: string) => `Loaded save from ${savedAt}.`,
  saveStatusError: (message: string) => `Save failed. ${message}`,
  eventPanelLabel: "Pending event",
  eventForCharacter: (characterName: string, year: number) => `${characterName}, year ${year}`,
  globalSearchLabel: "Search",
  globalSearchPlaceholder: "Search characters and cities",
  globalSearchResultsLabel: "Search results",
  globalSearchCharacterKindLabel: "Character",
  globalSearchCityKindLabel: "City",
  globalSearchCityLocation: (planetName: string, countryName: string) =>
    `${countryName}, ${planetName}`,
  globalSearchNoResults: (query: string) => `No characters or cities match "${query}".`,
};
